# Generated by Django 2.2 on 2019-04-06 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190406_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='arrival_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product_photo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='webapp.Product', verbose_name='Фото продукта'),
        ),
    ]
