# Generated by Django 2.2 on 2019-04-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190406_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='arrival_date',
            field=models.DateTimeField(verbose_name='Время создания'),
        ),
    ]
